name: CI Pipeline

on:
  push:
    branches: [ main, auto-test-pipeline ]
  pull_request:
    branches: [ main ]

jobs:

  # ----------- STAGE 1: Backend + Frontend Unit Tests -----------
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start database (if backend needs it)
        run: docker compose up -d db

      - name: Show DB status
        run: docker compose ps db

      - name: Run backend tests
        run: docker compose run --rm api npm test

      - name: Run frontend tests
        run: docker compose run --rm frontend npm test


  # ----------- STAGE 2: Integration + E2E Tests -----------
  integration-and-e2e:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - uses: actions/checkout@v4

      - name: Start full stack
        run: docker compose up -d --build

      - name: Show services
        run: docker compose ps

      - name: Run Integration tests
        run: docker compose run --rm api npm run test:integration

      - name: Run E2E tests
        run: docker compose run --rm frontend npm run cypress:run

      - name: Stop all services
        if: always()
        run: docker compose down
