name: CI/CD Pipeline

on:
  push:
    branches: [ main, auto-test-pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start database
        run: docker compose up -d db

      - name: Show DB status
        run: docker compose ps db

      - name: Run backend tests
        run: docker compose run --rm api npm test


  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run frontend tests
        run: docker compose run --rm frontend npm test


  integration-tests:
    runs-on: ubuntu-latest
    needs: backend-tests 

    steps:
      - uses: actions/checkout@v4

      - name: Start database
        run: docker compose up -d db

      - name: Run backend integration tests
        run: docker compose run --rm api npm run test:integration

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]

    steps:
      - uses: actions/checkout@v4

      - name: Start full stack
        run: docker compose up -d --build

      - name: Show running services
        run: docker compose ps

      - name: Run E2E tests
        run: docker compose run --rm frontend npm run cypress:run

      - name: Stop services
        if: always()
        run: docker compose down
